const groups={subject:['cinematic portrait','luxury product','fantasy landscape','character sheet','architectural concept','fashion editorial','game asset','brand campaign'],style:['photoreal','anime','isometric 3D','oil painting','cyberpunk','minimal Swiss design','clay render','bioluminescent'],lighting:['golden hour','softbox studio','volumetric light','neon rim light','moonlit','high-key','low-key chiaroscuro','subsurface glow'],camera:['35mm lens','macro detail','drone view','symmetrical composition','depth of field','Dutch angle','wide establishing shot','close-up'],quality:['ultra detailed','clean text rendering','8k texture','commercial ready','sharp focus','high coherence','premium color grading','artifact-free'],motion:['ready for animation','dynamic pose','wind-swept','cinematic action','calm stillness','flowing fabric','particle trails','motion blur']};
const modelOptions=['GPT Image / conversational edit','Midjourney-style cinematic','Flux fast local','Ideogram text-first','Firefly commercial-safe','Leonardo creative suite','Nano Banana edit fidelity'];
const aspects=['1:1 square','16:9 cinematic','9:16 story','4:5 social','3:2 photo','21:9 ultrawide'];
const quality=['Draft fast','Balanced','HD detail','Ultra production'];
const $=id=>document.getElementById(id);const state={active:new Map(),selected:null,reference:null};
function init(){fillSelect('model',modelOptions);fillSelect('aspect',aspects);fillSelect('quality',quality);$('corePrompt').value='A solar-powered floating city above a turquoise ocean, designed for optimistic climate fiction';$('negativePrompt').value='blurry, warped anatomy, extra fingers, unreadable text, watermark, low resolution, duplicated subjects';renderTags();bind();updatePrompt();generate();}
function fillSelect(id,items){$(id).innerHTML=items.map(x=>`<option>${x}</option>`).join('')}
function renderTags(){const wrap=$('tagGroups');wrap.innerHTML='';Object.entries(groups).forEach(([kind,tags])=>{const g=document.createElement('section');g.className='group';g.innerHTML=`<h3>${kind}</h3><div class="tags"></div>`;tags.forEach(text=>{const b=document.createElement('button');b.className='tag';b.dataset.kind=kind;b.textContent=text;b.onclick=()=>toggleTag(kind,text,b);g.querySelector('.tags').append(b)});wrap.append(g)})}
function toggleTag(kind,text,b){const key=`${kind}:${text}`;state.active.has(key)?state.active.delete(key):state.active.set(key,{kind,text});b.classList.toggle('active');updatePrompt()}
function promptParts(){const parts=[{kind:'subject',text:$('corePrompt').value.trim()}].filter(p=>p.text);state.active.forEach(v=>parts.push(v));if(state.reference)parts.push({kind:'camera',text:`use reference image as ${$('referenceWeight').value}% guidance`});return parts}
function finalPrompt(){return promptParts().map(p=>p.text).join(', ')+`, ${$('aspect').value}, ${$('model').value}, style strength ${$('styleStrength').value}`}
function updatePrompt(){const html=promptParts().map(p=>`<span class="chip ${p.kind}">${escapeHtml(p.text)}</span>`).join(' ');$('promptPreview').innerHTML=html||'<span class="muted">Start typing or activate tags.</span>';['styleStrength','referenceWeight'].forEach(id=>$(id+'Out').value=$(id).value)}
function randomPick(arr){return arr[Math.floor(Math.random()*arr.length)]}
function randomizeAll(){document.querySelectorAll('.tag.active').forEach(b=>b.classList.remove('active'));state.active.clear();Object.entries(groups).forEach(([kind,tags])=>{for(let i=0;i<(kind==='quality'?2:1);i++){const text=randomPick(tags),key=`${kind}:${text}`;state.active.set(key,{kind,text});[...document.querySelectorAll('.tag')].find(b=>b.dataset.kind===kind&&b.textContent===text)?.classList.add('active')}});$('seed').value=Math.floor(Math.random()*99999999);updatePrompt();generate()}
function mergePrevious(){const previous=$('previousPrompt').value.trim();if(!previous)return;const core=$('corePrompt');core.value=[core.value.trim(),previous].filter(Boolean).join(' | evolved from: ');updatePrompt()}
function generate(){const gallery=$('gallery');gallery.innerHTML='';const n=Math.min(8,Math.max(1,+$('count').value||4));for(let i=0;i<n;i++)gallery.append(renderCard(i))}
function renderCard(i){const t=$('cardTemplate').content.firstElementChild.cloneNode(true),c=t.querySelector('canvas'),ctx=c.getContext('2d');const seed=(+$('seed').value||1)+i*97;paint(ctx,c.width,c.height,seed);t.querySelector('strong').textContent=`Variant ${i+1} · ${$('quality').value}`;t.querySelector('p').textContent=finalPrompt().slice(0,130)+'…';t.onclick=()=>{document.querySelectorAll('.image-card').forEach(x=>x.classList.remove('selected'));t.classList.add('selected');state.selected=t.querySelector('p').textContent};return t}
function paint(ctx,w,h,seed){let x=seed;const rnd=()=>((x=(x*1664525+1013904223)>>>0)/4294967296);const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,`hsl(${rnd()*360},85%,55%)`);grad.addColorStop(.55,`hsl(${rnd()*360},80%,35%)`);grad.addColorStop(1,'#080b16');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);for(let i=0;i<42;i++){ctx.fillStyle=`hsla(${rnd()*360},90%,70%,${.08+rnd()*.18})`;ctx.beginPath();ctx.arc(rnd()*w,rnd()*h,20+rnd()*130,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=2;for(let i=0;i<9;i++){ctx.strokeRect(40+i*18,80+i*15,w-80-i*36,h-160-i*30)}}
function downloadPrompt(){const data={prompt:finalPrompt(),negative:$('negativePrompt').value,settings:{model:$('model').value,aspect:$('aspect').value,quality:$('quality').value,count:$('count').value,styleStrength:$('styleStrength').value,referenceWeight:$('referenceWeight').value,seed:$('seed').value},tags:[...state.active.values()]};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:'ruflo-vision-prompt.json'});a.click();URL.revokeObjectURL(a.href)}
function bind(){['corePrompt','negativePrompt','model','aspect','quality','count','styleStrength','referenceWeight','seed'].forEach(id=>$(id).addEventListener('input',updatePrompt));$('randomizeAll').onclick=randomizeAll;$('generate').onclick=generate;$('mergePrevious').onclick=mergePrevious;$('clearTags').onclick=()=>{state.active.clear();document.querySelectorAll('.tag.active').forEach(b=>b.classList.remove('active'));updatePrompt()};$('copyPrompt').onclick=()=>navigator.clipboard?.writeText(finalPrompt());$('downloadPrompt').onclick=downloadPrompt;$('iterateSelected').onclick=()=>{$('previousPrompt').value=state.selected||finalPrompt();mergePrevious()};$('referenceImage').onchange=e=>{const f=e.target.files[0];state.reference=f?.name;$('referenceStatus').textContent=f?`Using ${f.name}`:'Drop or choose an image';updatePrompt()}}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();
